# obtained from:
# https://github.com/catppuccin/atuin/blob/abfab12de743aa73cf20ac3fa61e450c4d96380c/themes/mocha/catppuccin-mocha-mauve.toml
[theme]
name = "catppuccin"

[colors]
AlertInfo = "#a6e3a1"
AlertWarn = "#fab387"
AlertError = "#f38ba8"
Annotation = "#cba6f7"
Base = "#cdd6f4"
Guidance = "#9399b2"
Important = "#f38ba8"
Title = "#cba6f7"
