[unstable]
codegen-backend = true
feature-unification = true

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-Clink-arg=--ld-path=wild"]

[target.x86_64-pc-windows-msvc]
# Faster linker on Windows than the default `link.exe`
linker = "rust-lld.exe"

[profile.dev]
# Use `cranelift` backend instead of the `llvm` while developing, for faster compile speeds
#codegen-backend = "cranelift"
# Don't include debug information.
debug = false
# Strip everything
strip = "symbols"

# Separate profile just for debugging with a debugger, once in a blue moon
[profile.debug]
inherits = "dev"
debug = true
strip = "none"

[build]
# Rust parallel frontend for further compilation speed increases
rustflags = ["-Z", "threads=8"]
rustc-wrapper = "sccache"

[resolver]
# reuse more dependency builds by ensuring the same set of dependency features
# are activated, independent of which package you are currently building and testing.
feature-unification = "workspace"